ENABLE:
    - CSS
    - JAVASCRIPT
    - JSON
    - JSX
    - MARKDOWN
    - REPOSITORY
    - TYPESCRIPT
    - TSX
    - YAML

DISABLE_LINTERS:
    - REPOSITORY_KICS
    - REPOSITORY_TRUFFLEHOG
    - YAML_V8R
