# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all

ENABLE:
    - CSS
    - JAVASCRIPT
    - JSON
    - JSX
    - MARKDOWN
    - REPOSITORY
    - TYPESCRIPT
    - TSX
    - YAML
