IGNORED_PATHS:
    - ".github/workflows/"

ENABLE:
    - CSS
    - JAVASCRIPT
    - JSON
    - JSX
    - MARKDOWN
    - REPOSITORY
    - TYPESCRIPT
    - TSX
    - YAML

DISABLE_ERRORS_LINTERS:
    - CSS_STYLELINT
    - REPOSITORY_KICS
