---
name: Linters

on:
    push:

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:
    megalinter:
        name: MegaLinter
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  fetch-depth: 0

            - name: MegaLinter
              uses: oxsecurity/megalinter@e08c2b05e3dbc40af4c23f41172ef1e068a7d651
              id: ml
              env:
                  APPLY_FIXES: all
                  APPLY_FIXES_EVENT: pull_request
                  APPLY_FIXES_MODE: commit
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  REPORT_OUTPUT_FOLDER: none
                  SHOW_ELAPSED_TIME: true
                  VALIDATE_ALL_CODEBASE: >-
                      ${{
                        github.event_name == 'push' &&
                        contains(fromJSON('["refs/heads/main"]'), github.ref)
                      }}

            - name: Prepare commit
              run: sudo chown -Rc $UID .git/

            - name: Commit and push applied linter fixes
              # cspell:ignore stefanzweifel
              uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0
              with:
                  commit_message: "fix(mega-linter): apply linters fixes"
                  commit_user_name: megalinter-bot
                  commit_user_email: nicolas.vuillamy@ox.security
                  file_pattern: |
                      .
                      :!/.github/workflows/**

            - name: Generate release artefact
              uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
              with:
                  name: New release
                  path: /home/runner/work/website_cv/website_cv
