name: MegaLinter

on:
    push:

jobs:
    megalinter:
        name: MegaLinter
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run Mega-Linter
              id: megalinter
              uses: oxsecurity/megalinter@v8
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  APPLY_FIXES: all
                  APPLY_FIXES_EVENT: commit
                  APPLY_FIXES_MODE: commit

            - name: Import GPG key
              uses: crazy-max/ghaction-import-gpg@v6
              with:
                  gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                  passphrase: ${{ secrets.PASSPHRASE }}
                  trust_level: 5

            - name: List keys
              run: gpg -K
