name: MegaLinter

on:
    push:

jobs:
    megalinter:
        name: MegaLinter
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run Mega-Linter
              uses: oxsecurity/megalinter@v8
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  APPLY_FIXES: all
                  APPLY_FIXES_EVENT: all
                  APPLY_FIXES_MODE: commit

            - name: Commit and push fixes
              run: |
                  git config user.name "GitHub Action"
                  git config user.email "action@github.com"
                  git add .
                  git commit -m "[MegaLinter] Apply linters fixes [skip ci]" || echo "No changes to commit"
                  git push origin HEAD:${{ github.head_ref || github.ref_name }}
