name: MegaLinter

on:
    push:
    pull_request:
        branches:
            - main

jobs:
    megalinter:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set file permissions
              run: chmod -R u+w .

            - name: Run Mega-Linter
              uses: oxsecurity/megalinter@v8
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  APPLY_FIXES: true
