name: MegaLinter

on:
    push:

jobs:
    megalinter:
        name: MegaLinter
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run Mega-Linter
              id: megalinter
              uses: oxsecurity/megalinter@v8
              env:
                  GITHUB_TOKEN: ${{ secrets.PAT }}
                  APPLY_FIXES: all
                  APPLY_FIXES_EVENT: commit
                  APPLY_FIXES_MODE: commit

            - name: Archive production artifacts
              if: success() || failure()
              uses: actions/upload-artifact@v4
              with:
                  name: MegaLinter reports
                  path: |
                      megalinter-reports
                      mega-linter.log

            - name: Prepare commit
              if: steps.megalinter.outputs.has_updated_sources == 1
              run: sudo chown -Rc $UID .git/
            - name: Commit and push applied linter fixes
              if: steps.megalinter.outputs.has_updated_sources == 1
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  branch: ${{ github.head_ref || github.ref }}
                  commit_message: "[MegaLinter] Apply linters fixes"
                  commit_user_name: megalinter-bot
                  commit_user_email: nicolas.vuillamy@ox.security
              env:
                  GITHUB_TOKEN: ${{ secrets.PAT }}
