name: MegaLinter

on:
    pull_request:
        branches:
            - main

jobs:
    megalinter:
        name: MegaLinter
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run Mega-Linter
              uses: oxsecurity/megalinter@v8
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  APPLY_FIXES: all
                  APPLY_FIXES_EVENT: all
                  APPLY_FIXES_MODE: commit
